root = "."
tmp_dir = "tmp/worker"

[build]
  cmd = "go build -o tmp/worker/main ./cmd/worker"
  bin = "tmp/worker/main"
  delay = 500
  exclude_dir = ["tmp", "vendor", "docs", ".git"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "toml", "env"]
  kill_delay = "500ms"
  send_interrupt = true

[log]
  level = "info"
  time = false

[color]
  main = "cyan"
  watcher = "yellow"
  build = "green"
  runner = "blue"

[misc]
  clean_on_exit = true
