version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
  exclusions:
    rules:
    # Testes podem ter erros não verificados
      - path: _test\.go
        linters: [errcheck]

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/prefeitura-rio/app-catalogo
